# coding: utf-8

"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.species_api import SpeciesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSpeciesApi(unittest.TestCase):
    """SpeciesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.species_api.SpeciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_species_get(self):
        """Test case for species_get

        Species  # noqa: E501
        """
        pass

    def test_species_id_get(self):
        """Test case for species_id_get

        Species ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
