# coding: utf-8

"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import studio_ghibli_api_sdk
from studio_ghibli_api_sdk.api.vehicles_api import VehiclesApi  # noqa: E501
from studio_ghibli_api_sdk.rest import ApiException


class TestVehiclesApi(unittest.TestCase):
    """VehiclesApi unit test stubs"""

    def setUp(self):
        self.api = studio_ghibli_api_sdk.api.vehicles_api.VehiclesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vehicles_get(self):
        """Test case for vehicles_get

        Vehicles  # noqa: E501
        """
        pass

    def test_vehicles_id_get(self):
        """Test case for vehicles_id_get

        Vehicle ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
