# coding: utf-8

"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.locations import Locations  # noqa: E501
from swagger_client.rest import ApiException


class TestLocations(unittest.TestCase):
    """Locations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocations(self):
        """Test Locations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.locations.Locations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
