# coding: utf-8

"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import studio_ghibli_api_sdk
from studio_ghibli_api_sdk.models.species import Species  # noqa: E501
from studio_ghibli_api_sdk.rest import ApiException


class TestSpecies(unittest.TestCase):
    """Species unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecies(self):
        """Test Species"""
        # FIXME: construct object with mandatory attributes with example values
        # model = studio_ghibli_api_sdk.models.species.Species()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
