# coding: utf-8

"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import studio_ghibli_api_sdk
from studio_ghibli_api_sdk.api.people_api import PeopleApi  # noqa: E501
from studio_ghibli_api_sdk.rest import ApiException


class TestPeopleApi(unittest.TestCase):
    """PeopleApi unit test stubs"""

    def setUp(self):
        self.api = studio_ghibli_api_sdk.api.people_api.PeopleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_people_get(self):
        """Test case for people_get

        Return all people  # noqa: E501
        """
        result = self.api.people_get()
        self.assertTrue(len(result) > 5)

    def test_people_id_get(self):
        """Test case for people_id_get

        People ID  # noqa: E501
        """
        result = self.api.people_id_get('ba924631-068e-4436-b6de-f3283fa848f0')
        self.assertEqual(result.id, 'ba924631-068e-4436-b6de-f3283fa848f0')


if __name__ == '__main__':
    unittest.main()
