# coding: utf-8

# flake8: noqa
"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.error import Error
from swagger_client.models.films import Films
from swagger_client.models.locations import Locations
from swagger_client.models.people import People
from swagger_client.models.species import Species
from swagger_client.models.vehicles import Vehicles
