# coding: utf-8

# flake8: noqa
"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from studio_ghibli_api_sdk.models.error import Error
from studio_ghibli_api_sdk.models.films import Films
from studio_ghibli_api_sdk.models.locations import Locations
from studio_ghibli_api_sdk.models.people import People
from studio_ghibli_api_sdk.models.species import Species
from studio_ghibli_api_sdk.models.vehicles import Vehicles
