# coding: utf-8

"""
    Studio Ghibli API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class People(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'gender': 'str',
        'age': 'str',
        'eye_color': 'str',
        'hair_color': 'str',
        'films': 'str',
        'species': 'str',
        'url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'gender': 'gender',
        'age': 'age',
        'eye_color': 'eye_color',
        'hair_color': 'hair_color',
        'films': 'films',
        'species': 'species',
        'url': 'url'
    }

    def __init__(self, id=None, name=None, gender=None, age=None, eye_color=None, hair_color=None, films=None, species=None, url=None):  # noqa: E501
        """People - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._gender = None
        self._age = None
        self._eye_color = None
        self._hair_color = None
        self._films = None
        self._species = None
        self._url = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if gender is not None:
            self.gender = gender
        if age is not None:
            self.age = age
        if eye_color is not None:
            self.eye_color = eye_color
        if hair_color is not None:
            self.hair_color = hair_color
        if films is not None:
            self.films = films
        if species is not None:
            self.species = species
        if url is not None:
            self.url = url

    @property
    def id(self):
        """Gets the id of this People.  # noqa: E501

        Unique identifier representing a specific person  # noqa: E501

        :return: The id of this People.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this People.

        Unique identifier representing a specific person  # noqa: E501

        :param id: The id of this People.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this People.  # noqa: E501

        Name of the person  # noqa: E501

        :return: The name of this People.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this People.

        Name of the person  # noqa: E501

        :param name: The name of this People.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def gender(self):
        """Gets the gender of this People.  # noqa: E501

        Gender of the person  # noqa: E501

        :return: The gender of this People.  # noqa: E501
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this People.

        Gender of the person  # noqa: E501

        :param gender: The gender of this People.  # noqa: E501
        :type: str
        """

        self._gender = gender

    @property
    def age(self):
        """Gets the age of this People.  # noqa: E501

        Age, if known, of the person  # noqa: E501

        :return: The age of this People.  # noqa: E501
        :rtype: str
        """
        return self._age

    @age.setter
    def age(self, age):
        """Sets the age of this People.

        Age, if known, of the person  # noqa: E501

        :param age: The age of this People.  # noqa: E501
        :type: str
        """

        self._age = age

    @property
    def eye_color(self):
        """Gets the eye_color of this People.  # noqa: E501

        Eye color of the person  # noqa: E501

        :return: The eye_color of this People.  # noqa: E501
        :rtype: str
        """
        return self._eye_color

    @eye_color.setter
    def eye_color(self, eye_color):
        """Sets the eye_color of this People.

        Eye color of the person  # noqa: E501

        :param eye_color: The eye_color of this People.  # noqa: E501
        :type: str
        """

        self._eye_color = eye_color

    @property
    def hair_color(self):
        """Gets the hair_color of this People.  # noqa: E501

        Hair color of the person  # noqa: E501

        :return: The hair_color of this People.  # noqa: E501
        :rtype: str
        """
        return self._hair_color

    @hair_color.setter
    def hair_color(self, hair_color):
        """Sets the hair_color of this People.

        Hair color of the person  # noqa: E501

        :param hair_color: The hair_color of this People.  # noqa: E501
        :type: str
        """

        self._hair_color = hair_color

    @property
    def films(self):
        """Gets the films of this People.  # noqa: E501

        Array of films the person appears in  # noqa: E501

        :return: The films of this People.  # noqa: E501
        :rtype: str
        """
        return self._films

    @films.setter
    def films(self, films):
        """Sets the films of this People.

        Array of films the person appears in  # noqa: E501

        :param films: The films of this People.  # noqa: E501
        :type: str
        """

        self._films = films

    @property
    def species(self):
        """Gets the species of this People.  # noqa: E501

        Species the person belongs to  # noqa: E501

        :return: The species of this People.  # noqa: E501
        :rtype: str
        """
        return self._species

    @species.setter
    def species(self, species):
        """Sets the species of this People.

        Species the person belongs to  # noqa: E501

        :param species: The species of this People.  # noqa: E501
        :type: str
        """

        self._species = species

    @property
    def url(self):
        """Gets the url of this People.  # noqa: E501

        Unique url of the person  # noqa: E501

        :return: The url of this People.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this People.

        Unique url of the person  # noqa: E501

        :param url: The url of this People.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, People):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
